name: i18n-ai-translate
description: Use ChatGPT or Google Gemini to automatically translate your i18n JSON on every PR
author: Taaha Mahdi

inputs:
  json-file-path:
    description: 'Path to the source i18n JSON file'
    required: true
  api-key:
    description: 'The API key for ChatGPT or Gemini'
    required: true

  author-email:
    description: 'The email of the person to attribute the i18n change to'
    required: false
    default: 'tmahdi+i18n-ai-translate@proton.me'
  author-name:
    description: 'The name of the person to attribute the i18n change to'
    required: false
    default: 'Taaha Mahdi'
  language:
    description: 'Language to translate from'
    required: false
    default: 'English'
  engine:
    description: 'Engine to use for translation ("chatgpt" or "gemini")'
    required: false
    default: 'chatgpt'
  model:
    description: 'Model to use for the translation (e.g., gpt-4o, gpt-4, gpt-3.5-turbo, gemini-pro)'
    required: false
    default: 'gpt-4o'
  templated-string-prefix:
    description: 'Prefix for templated strings'
    required: false
    default: "{{"
  templated-string-suffix:
    description: 'Suffix for templated strings'
    required: false
    default: "}}"
  batch-size:
    description: 'How many keys to process at a time'
    required: false
    default: 32

runs:
  using: 'composite'
  steps:
  - name: Checkout Repo
    uses: actions/checkout@v3
    with:
      ref: ${{ github.head_ref }}
      fetch-depth: 0

  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: '18'

  - name: Install Dependencies
    shell: bash
    run: |
      yarn add i18n-ai-translate

  - name: Copy .env for CI
    shell: bash
    run: |
      echo "OPENAI_API_KEY=${{ inputs.api-key }}" >> .env

  - name: Fetch original translation
    shell: bash
    run: |
      cp "${{ inputs.json-file-path }}" "${{ inputs.json-file-path }}-latest"
      git checkout origin/${{ github.base_ref }} -- "${{ inputs.json-file-path }}"

  - name: Translate the diff
    shell: bash
    run: |
      npx i18n-ai-translate diff \
        -b "${{ inputs.json-file-path }}" \
        -a "${{ inputs.json-file-path }}-latest" \
        -l "${{ inputs.language }}" \
        --verbose \
        --engine "${{ inputs.engine }}" \
        --model "${{ inputs.model }}" \
        -p "${{ inputs.templated-string-prefix }}" \
        -s "${{ inputs.templated-string-suffix }}" \
        -n "${{ inputs.batch-size }}"

  - name: Setup Git Config
    shell: bash
    run: |
      git config --global user.email "${{ inputs.author-email }}}"
      git config --global user.name "${{ inputs.author-name }}}"

  - name: Remove dependencies to prevent being merged
    shell: bash
    run: |
      yarn remove i18n-ai-translate

  - name: Commit the difference
    shell: bash
    run: |
      mv "${{ inputs.json-file-path }}-latest" "${{ inputs.json-file-path }}"
      git add **/*json
      git commit -m "Update translations" || echo "No changes to commit"
      git push
